### ISSUE TITLE
installation does not work

### ISSUE THREAD

**Issue by Sajonara** [lloeki/xbox_one_controller#1]
Hello Loic,

I’d like to thank you for your efforts with the xbox one controller usb driver for os x.

I changed os x to dev mode, rebooted the system and copied the kext file to the extensions folder, I changed the ownership with chown accordingly and afterwards I used kextload to load the extension but it always says the following:

xbox_one_controller.kext failed to load - (libkern/kext) authentication failure (file ownership/permissions);

I also chmodded the file anew but the problem persists.

Any idea?

Kind regards,

Alexander

**Comment by lloeki** [comment]
> xbox_one_controller.kext failed to load - (libkern/kext) authentication failure (file ownership/permissions);

This points to wrong permissions. A surefire way to have the permissions right is to do:

``` bash
sudo rm -rf /Library/Extensions/xbox_one_controller.kext            # just to be sure
sudo cp -R ~/Downloads/or/whatever/xbox_one_controller.kext /tmp    # this should set the ownership and permissions straight
sudo cp -R /tmp/xbox_one_controller.kext /Library/Extensions        # third-party kexts are autoloaded from there on Yosemite
```

Once this is done you can reboot, which should pick up the kext automatically. Alternatively you can  `sudo kextload /Library/Extensions/xbox_one_controller.kext` to load it right now manually.

You can always do a quick look up in Console.app for relevant log messages by filtering on 'xbox'.

I will be putting up a quick install script to ease installation.

**Comment by lloeki** [comment]
For reference, permissions should be:

``` bash
$ ls -ld /Library/Extensions/xbox_one_controller.kext               
drwxr-xr-x  3 root  wheel  102 Feb  6 21:34 /Library/Extensions/xbox_one_controller.kext
```

**Comment by Sajonara** [comment]
Thx a lot. Now it works.

I don't know why but I guess finder was the problem or the fact that I did not make a temporary copy of the file, because I did not copy the kext file via cli but directly via finder in the first place.

I wanted to try it out before writing about it for an online magazine. Very appreciating your help.

**Comment by lloeki** [comment]
Nice!

Be wary that all that games will lack now is button mappings. For example OpenEmu works fine since it allows the user to map actions to buttons, but some games do not and it's up to the developer to add mappings (as is the case for any other gamepad).

**Comment by Sajonara** [comment]
I recognised this trying Steam Big Picture Mode. With the Gamepad connected it won't start (under 10.10.3 Beta 1), though disconnecting it, starting Big Picture Mode and then connecting the gamepad works fine. And Steam allows the action mapping as well, hence the games optimised for Big Picture should work fine.

Thx a lot. :)

**Comment by lloeki** [comment]
> And Steam allows the action mapping as well, hence the games optimised for Big Picture should work fine.

Thanks for that, since I never used Big Picture (and controller settings are not available anywhere else), I didn't know this was possible! I set up the controller via Big Picture and it works great in Fez and VVVVVV.

> With the Gamepad connected it won't start (under 10.10.3 Beta 1)

FWIW it started just fine for me on 10.10.2.

Many thanks for the report.

**Comment by lloeki** [comment]
@Sajonara v1.0.1 is released, has an installer and is no longer considered "rough on the edges" :-) See README update for details.

**Comment by Sajonara** [comment]
Does v1.0.1 mean you don't have to switch nvram boot arguments either? Or do people still need to change this? I'm just asking so I could describe it properly in the article I wrote. :) I played The Cave yesterday and your gamepad driver works like a charm. Thx again.

**Comment by lloeki** [comment]
> _Does v1.0.1 mean you don't have to switch nvram boot arguments either? Or do people still need to change this?_

If necessary, the installer takes care of setting it for the user, after asking its permission. v1.1 will be signed. I just completed the Apple developer registration process, and the certificate generation is pending, therefore it should be fine by the end of the week.

**Comment by lloeki** [comment]
@Sajonara if you want to track progress on code signing, see #2.
