### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by Leempi** [lloeki/xbox_one_controller#3]
Hey,

I was wondering if you had some instructions for uninstallation?

Both the drivers and reversing the kext disabling.

**Comment by Leempi** [comment]
Never mind, i think just delete the kext from Library/Extensions and sudo nvram boot-args=kext-dev-mode=0 right?

**Comment by lloeki** [comment]
- make sure that no controller is plugged
- `sudo kextunload /Library/Extensions/xbox_one_controller.kext` (optional, as this gets unloaded automatically after some time)
- `sudo rm -rf /Library/Extensions/xbox_one_controller.kext`
- `sudo nvram boot-args=""` (but first make sure there are no other flags with `nvram boot-args`)
- reboot
